# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-09 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cod_cate', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom_cate', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleOrdenPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pro', models.CharField(max_length=20)),
                ('cantidad', models.IntegerField()),
                ('precio_venta', models.CharField(max_length=20)),
                ('importe', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('cod_dis', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom_dis', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenPedido',
            fields=[
                ('num_ordenpedido', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.CharField(max_length=20)),
                ('cod_tipopago', models.CharField(max_length=30)),
                ('total', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('cod_prese', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom_pre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_producto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom_producto', models.CharField(max_length=30)),
                ('pre_venta', models.CharField(max_length=30)),
                ('pre_compra', models.CharField(max_length=30)),
                ('fecha_ven', models.CharField(max_length=30)),
                ('stock', models.CharField(max_length=30)),
                ('cod_cate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Categoria')),
                ('cod_pres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Presentacion')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('cod_proveedor', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nom_prov', models.CharField(max_length=20)),
                ('dr_prov', models.CharField(max_length=20)),
                ('telefono', models.IntegerField(verbose_name=10)),
                ('celular', models.IntegerField(verbose_name=10)),
                ('id_distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Distrito')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='cod_prove',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Proveedor'),
        ),
        migrations.AddField(
            model_name='detalleordenpedido',
            name='cod_pro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.Producto'),
        ),
    ]
