# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-09 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('num_boleta', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha', models.CharField(max_length=10)),
                ('subtotal', models.CharField(max_length=30)),
                ('descuento', models.CharField(max_length=30)),
                ('codi_empl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado')),
                ('num_ordenpedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.OrdenPedido')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empleados.Empleado'),
        ),
    ]
