# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0002_auto_20190809_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='codi_cli',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
        ),
        migrations.AddField(
            model_name='ordenpedido',
            name='codigo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
        ),
        migrations.AddField(
            model_name='ordenpedido',
            name='nombre_cliente',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
