# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-12 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20190812_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(blank=True, height_field='height_field', upload_to='', width_field='width_field'),
        ),
    ]
