# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-12 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_auto_20190812_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(upload_to='img'),
        ),
    ]
