# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-15 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_auto_20190813_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': set([('is_dos', 'Usuario Dos'), ('is_uno', 'Usuario Uno')])},
        ),
    ]
