# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-09 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cli', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre_cli', models.CharField(max_length=30)),
                ('dir_cli', models.CharField(max_length=30)),
                ('cod_dis', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=30)),
                ('ruc', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('celular', models.IntegerField()),
            ],
        ),
    ]
